import type { Stage, Step, TheoryQuestion } from '../types';

export const sources = {
  hk: 'https://www.hecklerkoch.eu/en/Products/Military%20and%20Law%20Enforcement/Assault%20rifles/G36',
  hkTechnical: 'https://hk-manuals.s3.amazonaws.com/files/Military/G36/G36_Technical_Data.pdf',
  hkParts: 'https://hkparts.net/hk-rifle-smg-parts/g36-sl8-series/',
  bw: 'http://bundzone.bplaced.net/images//dokumente/Zentralrichtlinie_GewehrG36.pdf',
};

const BW = 'Bundesvērs · A2-222/0-0-4741 “Das Gewehr G36”';
const HK = 'Heckler & Koch · G36 tehniskie dati';

// The order is the order supplied for the course. Movements follow the Bundeswehr manual.
export const steps: Step[] = [
  {
    id: 'sling', hint: 'atāķē abus galus', assemblyHint: 'iekabini abus galus', label: 'Noņemt siksnu', assemblyLabel: 'Piestiprināt siksnu', part: 'Siksna',
    function: 'Ļauj ieroci ērti pārnēsāt un noturēt pie ķermeņa.',
    explanation: 'Siksnas priekšējais āķis ir iekabināts pastobra priekšgalā, aizmugurējais – laides cilpā. Pirms izjaukšanas siksnu noņem, lai tā netraucētu darbu.',
    action: 'Atāķē siksnas abus galus un noņem siksnu.',
    assemblyAction: 'Iekabini siksnas āķus pastobra un laides cilpās.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'stock', hint: 'uz labo pusi', assemblyHint: 'atpakaļ līdz fiksatoram', label: 'Salocīt laidi', assemblyLabel: 'Atlocīt laidi', part: 'Laide',
    function: 'Balsta ieroci pret plecu un palīdz stabili tēmēt.',
    explanation: 'G36 laide saliekas uz ieroča labo pusi, un salocītā stāvoklī to notur čaulu atstarotājs. Salocīta laide atbrīvo korpusa aizmuguri, pa kuru vēlāk izņem atgriezējmehānismu un aizslēga kārbu.',
    action: 'Nospied laides fiksatoru un saloki laidi uz ieroča labo pusi.',
    assemblyAction: 'Atloki laidi atpakaļ, līdz fiksators to nofiksē.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'rear-pins', hint: 'uz kreiso pusi', assemblyHint: 'no kreisās puses', label: 'Izņemt aizmugurējo un centrālo tapu', assemblyLabel: 'Ievietot aizmugurējo un centrālo tapu',
    part: 'Aizmugurējā un centrālā tapa', plural: true,
    function: 'Stiprina pistoļveida rokturi pie korpusa; aizmugurējā tapa notur arī atgriezējmehānisma apakšdaļu.',
    explanation: 'Abas tapas šķērso korpusu un roktura korpusu. Laides apakšējā balstā ir trīs atveres, kurās uzglabā izņemto aizmugurējo, centrālo un priekšējo tapu, lai tās nepazustu.',
    action: 'Izspied abas tapas uz kreiso pusi un izvelc tās.',
    assemblyAction: 'Ievieto abas tapas no kreisās puses, līdz tās ir vienā līmenī ar korpusu.',
    tip: 'Skats ir no ieroča kreisās puses, tāpēc izspiestās tapas kustas pretī skatītājam.',
    assemblyTip: 'Skats ir no ieroča kreisās puses, tāpēc ievietojamās tapas kustas prom no skatītāja.',
    advice: 'Izņemtās tapas uzreiz ievieto laides uzglabāšanas atverēs – laidē ir trīs atveres: aizmugurējai, centrālajai un priekšējai tapai. Animācijā tapas noliktas uz paklāja tikai uzskatāmībai.',
    assemblyAdvice: 'Aizmugurējo un centrālo tapu ņem no laides uzglabāšanas atverēm.',
    term: 'Vāciski – Haltebolzen am Griffstück.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'trigger-group', hint: 'uz leju', assemblyHint: 'no apakšas', label: 'Izņemt pistoļveida rokturi ar šaušanas mehānismu', assemblyLabel: 'Uzstādīt pistoļveida rokturi ar šaušanas mehānismu',
    part: 'Pistoļveida rokturis ar šaušanas mehānismu',
    function: 'Nodrošina satvērienu un ietver šaušanas mehānismu – mēlīti, gaili un drošinātāju-pārslēdzēju.',
    explanation: 'Rokturī atrodas arī aizslēga aizturis. Pārslēdzējam ir trīs stāvokļi: drošinātājs (balts apzīmējums), atsevišķi šāvieni un automātiskā uguns (sarkani apzīmējumi).',
    action: 'Noņem rokturi virzienā uz leju.',
    assemblyAction: 'Ievieto rokturi korpusā no apakšas.',
    term: 'Vāciski – Griffstück mit Abzugseinrichtung.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'bolt-return', hint: 'uz leju, tad uz aizmuguri', assemblyHint: 'no aizmugures', label: 'Izņemt aizslēga atgriezējmehānismu', assemblyLabel: 'Ievietot aizslēga atgriezējmehānismu', part: 'Aizslēga atgriezējmehānisms',
    function: 'Noslēdz korpusu no aizmugures un ar atsperi atgriež aizslēga kārbu priekšējā stāvoklī.',
    explanation: 'Mehānismu veido aizmugurējais vāks ar buferi un atgriezējatspere ar vadstieni. Tā apakšdaļu notur aizmugurējā tapa, tāpēc to var izņemt tikai pēc roktura noņemšanas.',
    action: 'Piespied mehānismu uz leju, līdz augšējais izcilnis atbrīvojas, un izvelc to uz aizmuguri.',
    assemblyAction: 'Ievieto mehānismu no aizmugures un iespied augšējo izcilni korpusa atverē.',
    term: 'Vāciski – Bodenstück mit Schließfeder (aizmugurējais vāks ar atgriezējatsperi).',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'carrier', hint: 'uz aizmuguri', assemblyHint: 'no aizmugures', label: 'Izņemt aizslēga kārbu', assemblyLabel: 'Ievietot aizslēga kārbu', part: 'Aizslēga kārba',
    function: 'Nes aizslēgu un belzni un, kustoties turp un atpakaļ, pārlādē ieroci.',
    explanation: 'Aizslēga kārbā ir ievietots aizslēgs, belznis un pārlādēšanas rokturis. Abos sānos ir vadotnes, pa kurām tā slīd korpusā.',
    action: 'Ar pārlādēšanas rokturi pabīdi aizslēga kārbu atpakaļ un izņem to no korpusa.',
    assemblyAction: 'Ievieto aizslēga kārbu korpusa vadotnēs no aizmugures un iebīdi līdz galam.',
    tip: 'Pieturi aizslēga kārbu ar roku – izbīdot tā var izkrist no korpusa.',
    assemblyTip: 'Aizslēga kārbu iebīdi līdz galam, pirms ievieto atgriezējmehānismu.',
    term: 'Vāciski – Verschluss ar Verschlussträger (aizslēga rāmis).',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'magwell', hint: 'pagriez uz leju', assemblyHint: 'pagriez uz augšu', direction: 'pagriežas uz leju', label: 'Izņemt aptveres ligzdu', assemblyLabel: 'Uzstādīt aptveres ligzdu', part: 'Aptveres ligzda',
    function: 'Uztver aptveri un novieto to pareizā stāvoklī pret aizslēgu.',
    explanation: 'Ligzdu priekšpusē notur korpusa izciļņi, bet aizmugurē – aptveres aizturis. Tāpēc to noņem, pagriežot uz leju ap priekšējo stiprinājumu.',
    action: 'Nospied aptveres aizturi, pagriez ligzdu uz leju un noņem to.',
    assemblyAction: 'Iekabini ligzdas priekšpusi korpusa izciļņos un pagriez to uz augšu, līdz aizturis to nofiksē.',
    term: 'Vāciski – Magazinschacht.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'front-pin', hint: 'uz kreiso pusi', assemblyHint: 'no kreisās puses', label: 'Izņemt priekšējo tapu', assemblyLabel: 'Ievietot priekšējo tapu', part: 'Priekšējā tapa',
    function: 'Stiprina pastobru pie korpusa.',
    explanation: 'Tapa šķērso pastobra aizmugurējo daļu un korpusu. Pirms tapas izņemšanas satver pastobru, lai tas nenokristu.',
    action: 'Izvelc priekšējo tapu uz kreiso pusi.',
    assemblyAction: 'Ievieto priekšējo tapu no kreisās puses.',
    advice: 'Izņemto tapu uzreiz ievieto trešajā laides uzglabāšanas atverē, blakus aizmugurējai un centrālajai tapai. Animācijā tā nolikta uz paklāja tikai uzskatāmībai.',
    assemblyAdvice: 'Priekšējo tapu ņem no laides uzglabāšanas atveres.',
    term: 'Vāciski – Haltebolzen am Handschutz.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'handguard', hint: 'uz priekšu', assemblyHint: 'no priekšpuses', label: 'Noņemt pastobru', assemblyLabel: 'Uzlikt pastobru', part: 'Pastobrs',
    function: 'Aizsedz stobru un gāzu sistēmu, nodrošina satvērienu un pasargā roku no karsta stobra.',
    explanation: 'Pastobrs aptver stobru un gāzu sistēmu no visām pusēm. Tā atveres uzlabo stobra dzesēšanu, un G36 pastobram var piestiprināt Picatinny sliedes.',
    action: 'Novelc pastobru uz priekšu pāri stobram.',
    assemblyAction: 'Uzbīdi pastobru uz stobra no priekšpuses līdz korpusam.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'gas-return', hint: 'atpakaļ, sāņus, uz priekšu', assemblyHint: 'atpakaļ un vietā', label: 'Izņemt gāzu virzuļa atgriezējmehānismu', assemblyLabel: 'Ievietot gāzu virzuļa atgriezējmehānismu', part: 'Gāzu virzuļa atgriezējmehānisms',
    function: 'Pārnes virzuļa impulsu uz aizslēga kārbu, un tā atspere atgriež stieni sākumstāvoklī.',
    explanation: 'Mehānisms ir stienis ar atsperi virs stobra starp gāzu kameru un korpusu. Šāviena brīdī virzulis pagrūž stieni atpakaļ, un stienis ar triecienu atgrūž aizslēga kārbu.',
    action: 'Pavelc stieni atpakaļ pret atsperes spēku, pagriez to sāņus un izņem uz priekšu.',
    assemblyAction: 'Ievieto stieņa aizmugurējo galu korpusā, saspied atsperi un novieto priekšējo galu pret virzuli.',
    term: 'Vāciski – Antriebsstange mit Feder (virzuļa stienis ar atsperi).',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'piston', hint: 'uz aizmuguri', assemblyHint: 'no aizmugures', label: 'Izņemt virzuli', assemblyLabel: 'Ievietot virzuli', part: 'Virzulis',
    function: 'Pulvergāzu spiediena ietekmē virzās atpakaļ un iedarbina aizslēga mehānismu.',
    explanation: 'G36 izmanto īsgaitas gāzu virzuli: tas pārvietojas nelielu attālumu un nav savienots ar aizslēga kārbu, tāpēc korpuss mazāk piesārņojas.',
    action: 'Izvelc virzuli no gāzu kameras uz aizmuguri.',
    assemblyAction: 'Ievieto virzuli gāzu kamerā no aizmugures.',
    tip: 'Virzuļa smaili izmanto arī kā palīglīdzekli belžņa mehāniskās tapas izspiešanai.',
    term: 'Vāciski – Gaskolben.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'flash-hider', hint: 'noskrūvē', assemblyHint: 'uzskrūvē', label: 'Noskrūvēt liesmu slāpētāju', assemblyLabel: 'Uzskrūvēt liesmu slāpētāju', part: 'Liesmu slāpētājs',
    function: 'Izkliedē no stobra izplūstošās degošās pulvergāzes un samazina uzliesmojumu.',
    explanation: 'Liesmu slāpētājs ir uzskrūvēts uz stobra gala vītnes, un pret patvaļīgu atskrūvēšanos to nodrošina fiksācijas atspere. Tam ir atslēgas plaknes 17 mm uzgriežņu atslēgai.',
    action: 'Noskrūvē liesmu slāpētāju no stobra vītnes.',
    assemblyAction: 'Uzskrūvē liesmu slāpētāju līdz galam.',
    tip: 'Cieši pievilktu liesmu slāpētāju atskrūvē ar 17 mm uzgriežņu atslēgu.',
    assemblyTip: 'Uzskrūvē līdz galam: fiksācijas atspere neļauj liesmu slāpētājam patvaļīgi atskrūvēties.',
    term: 'Vāciski – Mündungsfeuerdämpfer.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'firing-pin-retainer', hint: 'uz kreiso pusi', assemblyHint: 'no kreisās puses', label: 'Izņemt belžņa mehānisko tapu', assemblyLabel: 'Ievietot belžņa mehānisko tapu', part: 'Belžņa mehāniskā tapa',
    function: 'Notur belzni aizslēga kārbā.',
    explanation: 'Tapa šķērso aizslēga kārbas aizmugurējo daļu un neļauj belznim izslīdēt uz aizmuguri.',
    action: 'Izspied tapu uz kreiso pusi.',
    assemblyAction: 'Ievieto tapu no kreisās puses un iespied to līdz galam.',
    tip: 'Tapas izspiešanai var izmantot gāzu virzuļa smaili.',
    term: 'Vāciski – Sicherungsbolzen (belžņa fiksācijas tapa).',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'firing-pin', hint: 'uz aizmuguri', assemblyHint: 'no aizmugures', label: 'Izņemt belzni', assemblyLabel: 'Ievietot belzni', part: 'Belznis',
    function: 'Gaiļa trieciena ietekmē uzsit pa patronas kapseli un izraisa šāvienu.',
    explanation: 'G36 belznis ir brīvi kustīgs: to nevirza atspere, bet gaiļa trieciens. Kad fiksējošā tapa ir izņemta, belznis izslīd no aizslēga kārbas aizmugures.',
    action: 'Izvelc belzni no aizslēga kārbas uz aizmuguri.',
    assemblyAction: 'Ievieto belzni aizslēga kārbā no aizmugures.',
    term: 'Vāciski – Schlagbolzen.',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'bolt-pin', hint: 'uz kreiso pusi', assemblyHint: 'no kreisās puses', label: 'Izņemt aizslēga tapu', assemblyLabel: 'Ievietot aizslēga tapu', part: 'Aizslēga tapa',
    function: 'Savieno aizslēgu ar aizslēga kārbu un vadības rievā pagriež aizslēgu, to aizslēdzot un atslēdzot.',
    explanation: 'Tapa šķērso aizslēgu un slīd aizslēga kārbas slīpajā vadības rievā. Kārbai kustoties, rieva pagriež aizslēgu ap tā asi.',
    action: 'Pavelc aizslēgu nedaudz uz priekšu un izņem tapu uz kreiso pusi.',
    assemblyAction: 'Ievieto tapu no kreisās puses tā, lai tās plakanās virsmas būtu paralēlas stobram.',
    assemblyTip: 'Ja tapas plakanās virsmas nav paralēlas stobram, belzni nevar ievietot.',
    term: 'Vāciski – Steuerbolzen (aizslēga vadības tapa).',
    source: sources.bw, sourceName: BW,
  },
  {
    id: 'bolt', hint: 'uz priekšu', assemblyHint: 'no priekšpuses', label: 'Izņemt aizslēgu no aizslēga kārbas', assemblyLabel: 'Ievietot aizslēgu aizslēga kārbā', part: 'Aizslēgs',
    function: 'Ievirza patronu patrontelpā, pagriežoties aizslēdz stobru un pēc šāviena izvelk čaulu.',
    explanation: 'G36 ir rotējošs aizslēgs: pagriežoties tā izciļņi nofiksējas korpusā iestrādātajā slēgdetaļā. Aizslēgā ir arī čaulas izvilcējs un izmetējs.',
    action: 'Izvelc aizslēgu no aizslēga kārbas uz priekšu.',
    assemblyAction: 'Ievieto aizslēgu aizslēga kārbā no priekšpuses.',
    term: 'Vāciski – Verschlusskopf (aizslēga galva).',
    source: sources.bw, sourceName: BW,
  },
];

/** Not part of the scored order: always done before disassembly and after assembly. */
export const prep: Stage = {
  id: 'prep', label: 'Drošības pārbaude', part: 'Aptvere', hint: 'izņem aptveri, pārbaudi patrontelpu',
  action: 'Pārslēdz drošinātāju, izņem aptveri, atvelc pārlādēšanas rokturi un pārbaudi, vai patrontelpā nav patronas.',
  explanation: 'Pirms izjaukšanas vienmēr pārliecinies, ka ierocis ir izlādēts. Šis sagatavošanas solis nav iekļauts testa secībā.',
  source: sources.bw, sourceName: BW,
};

export const finalCheck: Stage = {
  id: 'check', label: 'Darbības pārbaude', part: 'Salikts ierocis', hint: 'atvelc un palaid aizslēgu',
  action: 'Atvelc un palaid aizslēgu, pārbaudi aizslēga aizturi un drošinātāju un pārliecinies, ka aizslēgs pilnībā aizslēdzas.',
  explanation: 'Pēc salikšanas pārbaudi darbību: drošinātāja stāvoklī mēlīti nevar nospiest, aizslēgs pilnībā aizslēdzas, un liesmu slāpētājs ir cieši pieskrūvēts.',
  source: sources.bw, sourceName: BW,
};

export const termNotes = steps.filter((step) => step.term);

export const technical = { calibre: '5,56 × 45 mm NATO', length: '1002 / 755 mm', barrel: '480 mm', source: sources.hkTechnical, sourceName: HK };

/** Technical data and operation, from the Heckler & Koch G36 technical data (G36 column). */
export const theory: TheoryQuestion[] = [
  { id: 'ammunition', prompt: 'Kādu munīciju izmanto G36?', correct: '5,56 × 45 mm NATO',
    wrong: ['7,62 × 51 mm NATO', '7,62 × 39 mm', '9 × 19 mm'],
    explanation: 'G36 saimes ieroči ir 5,56 × 45 mm NATO kalibrā.' },
  { id: 'magazine', prompt: 'Cik patronu ietilpst G36 standarta aptverē?', correct: '30',
    wrong: ['10', '20', '40'],
    explanation: 'Standarta aptverē ietilpst 30 patronas; pilna aptvere sver ap 510 g.' },
  { id: 'principle', prompt: 'Kāds ir G36 darbības princips?', correct: 'Pulvergāzes darbina gāzu virzuli, un aizslēgs pagriežas',
    wrong: ['Izmanto atsitiena enerģiju; aizslēga atvēršanos aizkavē bloķēšanas rullīši', 'Aizslēgu pēc katra šāviena pārlādē ar roku', 'Brīvais aizslēgs bez jebkādas aizkaves'],
    explanation: 'G36 ir gāzes darbības ierocis ar rotējošu aizslēgu: pulvergāzes caur gāzu virzuli dzen atpakaļ aizslēga kārbu, un aizslēgs pagriežas.' },
  { id: 'barrel', prompt: 'Kāds ir G36 stobra garums?', correct: '480 mm',
    wrong: ['228 mm', '318 mm', '450 mm'],
    explanation: 'G36 stobrs bez liesmu slāpētāja ir 480 mm garš (G36K – 318 mm, G36C – 228 mm).' },
  { id: 'length', prompt: 'Kāds ir G36 garums ar atlocītu un ar salocītu laidi pēc ražotāja datiem?', correct: '1002 un 755 mm',
    wrong: ['716 un 500 mm', '833 un 613 mm', '1045 mm, laide nesalokāma'],
    explanation: 'Ražotāja dati attiecas uz G36 ar standarta saliekamo laidi: 1002 mm ar atlocītu, 755 mm ar salocītu laidi. Ar regulējamu laidi garums atkarīgs no tās iestatījuma.' },
  { id: 'rate', prompt: 'Kāds ir G36 šaušanas temps?', correct: 'Ap 750 šāvienu minūtē',
    wrong: ['Ap 300 šāvienu minūtē', 'Ap 500 šāvienu minūtē', 'Ap 1200 šāvienu minūtē'],
    explanation: 'Šaušanas temps ir ap 750 šāvienu minūtē.' },
  { id: 'velocity', prompt: 'Kāds ir lodes sākumātrums, šaujot ar G36?', correct: 'Ap 920 m/s',
    wrong: ['Ap 350 m/s', 'Ap 750 m/s', 'Ap 1200 m/s'],
    explanation: 'Ar SS109 munīciju G36 lodes sākumātrums ir ap 920 m/s; īsākiem stobriem tas ir mazāks (G36K – ap 880 m/s, G36C – ap 750 m/s).' },
  { id: 'mass', prompt: 'Cik sver G36 bez aptveres?', correct: 'Ap 3,6 kg',
    wrong: ['Ap 2 kg', 'Ap 4,5 kg', 'Ap 6 kg'],
    explanation: 'Pēc ražotāja datiem G36 ar standarta laidi bez aptveres sver ap 3630 g (G36K – ap 3370 g, G36C – ap 2988 g).' },
  { id: 'material', prompt: 'No kāda materiāla izgatavota G36 stobra kārba, pastobrs un laide?', correct: 'No stikla šķiedru pastiprinātas plastmasas',
    wrong: ['No alumīnija sakausējuma', 'No tērauda', 'No koka'],
    explanation: 'Izņemot stobru un aizslēga mezglu, G36 galvenās detaļas ir no stikla šķiedru pastiprinātas plastmasas – tas samazina ieroča svaru.' },
  { id: 'pins', prompt: 'Kā G36 nepilnās izjaukšanas laikā atvieno galvenās sastāvdaļas?', correct: 'Bez instrumentiem, izbīdot trīs tapas',
    wrong: ['Ar skrūvgriezi, atskrūvējot četras skrūves', 'Ar speciālu atslēgu', 'Atskrūvējot vienu centrālo skrūvi'],
    explanation: 'G36 nepilnajai izjaukšanai instrumenti nav vajadzīgi: galvenās sastāvdaļas notur trīs tapas.' },
].map((question) => ({ ...question, source: sources.hkTechnical, sourceName: HK }));
